Example session using thrift_client:

118> f(), {ok, C} = thrift_client:start_link("localhost", 9090, thriftTest_thrif
t).
{ok,<0.271.0>}
119> thrift_client:call(C, testVoid, []).
{ok,ok}
120> thrift_client:call(C, testVoid, [asdf]).
{error,{bad_args,testVoid,[asdf]}}
121> thrift_client:call(C, testI32, [123]).
{ok,123}
122> thrift_client:call(C, testAsync, [1]).
{ok,ok}
123> catch thrift_client:call(C, testXception, ["foo"]).
{error,{no_function,testXception}}
124> catch thrift_client:call(C, testException, ["foo"]).
{ok,ok}
125> catch thrift_client:call(C, testException, ["Xception"]).
{xception,1001,"This is an Xception"}
126> thrift_client:call(C, testException, ["Xception"]).

=ERROR REPORT==== 24-Feb-2008::23:00:23 ===
Error in process <0.269.0> with exit value: {{nocatch,{xception,1001,"This is an
 Xception"}},[{thrift_client,call,3},{erl_eval,do_apply,5},{shell,exprs,6},{shel
l,eval_loop,3}]}

** exited: {{nocatch,{xception,1001,"This is an Xception"}},
            [{thrift_client,call,3},
             {erl_eval,do_apply,5},
             {shell,exprs,6},
             {shell,eval_loop,3}]} **
